name: nf-core-eager-2.1.0dev
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - anaconda::openjdk=8.0.152
  - bioconda::fastqc=0.11.8
  - bioconda::adapterremoval=2.3.1
  - bioconda::adapterremovalfixprefix=0.0.5
  - bioconda::bwa=0.7.17
  - bioconda::picard=2.20.7
  - bioconda::samtools=1.9
  - bioconda::dedup=0.12.5
  - bioconda::angsd=0.931
  - bioconda::circularmapper=1.93.4
  - bioconda::gatk4=4.1.3.0
  - bioconda::qualimap=2.2.2c
  - bioconda::vcf2genome=0.91
  - bioconda::damageprofiler=0.4.6
  - bioconda::multiqc=1.7
  - bioconda::pmdtools=0.60
  - bioconda::bedtools=2.29.0
  - conda-forge::r-rmarkdown=1.15
  - conda-forge::libiconv=1.15
  - conda-forge::pigz=2.3.4
  - bioconda::sequencetools=1.2.2
  - bioconda::preseq=2.0.3
  - bioconda::fastp=0.20.0
  - bioconda::bamutil=1.0.14
  - bioconda::mtnucratio=0.5
  - pysam=0.15.3
  - python=3.7.1
  - freebayes=1.3.1
  - sexdeterrmine=1.0
  - bioconda::multivcfanalyzer=0.85.1
  #Missing Schmutzi,snpAD
