name: nf-core-eager-2.1.0dev
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - defaults::openjdk=8.0.152
  - fastqc=0.11.8
  - adapterremoval=2.2.2
  - adapterremovalfixprefix=0.0.4
  - bwa=0.7.17
  - picard=2.18.15
  - samtools=1.9
  - dedup=0.12.3
  - angsd=0.923
  - circularmapper=1.93.4
  - gatk4=4.0.10.0
  - qualimap=2.2.2b
  - vcf2genome=0.91
  - damageprofiler=0.3.11
  - multiqc=1.6
  - pmdtools=0.60
  - r-rmarkdown=1.10
  - libiconv=1.15
  - sequencetools=1.2.2
  - preseq=2.0.3
  - fastp=0.19.4
  - bamutil=1.0.14
  #Missing Schmutzi,snpAD
