# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-eager-2.4.6
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.4
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.2
  - conda-forge::pygments=2.9.0
  - bioconda::rename=1.601
  - conda-forge::openjdk=8.0.144 # Don't upgrade - required for GATK
  - bioconda::fastqc=0.11.9
  - bioconda::adapterremoval=2.3.2
  - bioconda::adapterremovalfixprefix=0.0.5
  - bioconda::bwa=0.7.17
  - bioconda::picard=2.26.0
  - bioconda::samtools=1.12
  - bioconda::dedup=0.12.8
  - bioconda::angsd=0.935
  - bioconda::circularmapper=1.93.5
  - bioconda::gatk4=4.2.0.0
  - bioconda::gatk=3.5 ## Don't upgrade - required for MultiVCFAnalyzer
  - bioconda::qualimap=2.2.2d
  - bioconda::vcf2genome=0.91
  - bioconda::damageprofiler=0.4.9 # Don't upgrade - later versions don't allow java 8
  - bioconda::multiqc=1.13
  - bioconda::pmdtools=0.60
  - bioconda::bedtools=2.30.0
  - conda-forge::libiconv=1.16
  - conda-forge::pigz=2.6
  - bioconda::sequencetools=1.5.2
  - bioconda::preseq=3.1.2
  - bioconda::fastp=0.20.1
  - bioconda::bamutil=1.0.15
  - bioconda::mtnucratio=0.7
  - bioconda::pysam=0.16.0
  - bioconda::kraken2=2.1.2
  - conda-forge::pandas=1.2.4
  - bioconda::freebayes=1.3.5
  - bioconda::sexdeterrmine=1.1.2
  - bioconda::multivcfanalyzer=0.85.2
  - bioconda::hops=0.35
  - bioconda::malt=0.61
  - conda-forge::biopython=1.79
  - conda-forge::xopen=1.1.0
  - bioconda::bowtie2=2.4.4
  - bioconda::eigenstratdatabasetools=1.0.2
  - bioconda::mapdamage2=2.2.1
  - bioconda::bbmap=38.92
  - bioconda::bcftools=1.12