name: nf-core-eager-2.2.0dev
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bioconda::rename=1.601
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::markdown=3.1.1 #Dont upgrade anymore â€š
  - conda-forge::openjdk=8.0.144
  - bioconda::fastqc=0.11.9
  - bioconda::adapterremoval=2.3.1
  - bioconda::adapterremovalfixprefix=0.0.5
  - bioconda::bwa=0.7.17
  - bioconda::picard=2.22.0
  - bioconda::samtools=1.9
  - bioconda::dedup=0.12.6
  - bioconda::angsd=0.933
  - bioconda::circularmapper=1.93.4
  - bioconda::gatk4=4.1.4.1
  - bioconda::qualimap=2.2.2d
  - bioconda::vcf2genome=0.91
  - bioconda::damageprofiler=0.4.9
  - bioconda::multiqc=1.9
  - bioconda::pmdtools=0.60
  - bioconda::bedtools=2.29.2
  - conda-forge::libiconv=1.15
  - conda-forge::pigz=2.3.4
  - bioconda::sequencetools=1.2.2
  - bioconda::preseq=2.0.3
  - bioconda::fastp=0.20.0
  - bioconda::bamutil=1.0.14
  - bioconda::mtnucratio=0.7
  - pysam=0.15.4
  - python=3.8.3
  - bioconda::kraken2=2.0.8_beta
  - conda-forge::pandas=1.0.1
  - bioconda::freebayes=1.3.2
  - bioconda::sexdeterrmine=1.1.1
  - bioconda::multivcfanalyzer=0.85.1
  - bioconda::hops=0.34
  - conda-forge::biopython=1.76
  - conda-forge::xopen=0.8.4
  - bioconda::bowtie2=2.4.1
  #Missing Schmutzi,snpAD
